pr:
  - master

trigger:
  - master

variables:
  - group: fabric-variables

pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      node common/scripts/install-run-rush.js install --bypass-policy
    displayName: rush install

  - script: |
      npm run checkchange
    displayName: check change

  - script: |
      npm run buildci
    displayName: build ci

  - task: AzureUpload@1
    displayName: AzureUpload
    inputs:
      SourcePath: 'apps/pr-deploy-site/dist'
      azureSubscription: 'UI Fabric (bac044cf-49e1-4843-8dda-1ce9662606c8)'
      storage: fabricweb
      ContainerName: '$web'
      BlobPrefix: 'pr-deploy-site/$(Build.SourceBranch)'

  - script: |
      npm run perf-test
    displayName: perf test

  - task: GithubPRComment@0
    displayName: 'Post Perf Results to Github Pull Request'
    inputs:
      githubOwner: OfficeDev
      githubRepo: 'office-ui-fabric-react'
      blobFilePath: '$(Build.SourcesDirectory)/$(PerfCommentFilePath)'
      status: '$(PerfCommentStatus)'
      uniqueId: 'perfComment9423'

  - task: GithubPRStatus@0
    displayName: 'Update Github Pull Request Status'
    inputs:
      githubOwner: OfficeDev
      githubRepo: 'office-ui-fabric-react'
      githubContext: 'Pull Request Deployed Site'
      githubDescription: 'Click "Details" to go to the Deployed Site'
      githubTargetLink: 'http://fabricweb.z5.web.core.windows.net/pr-deploy-site/$(Build.SourceBranch)/'

  - script: |
      npm run a11ytest
    displayName: run a11y tests

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: './apps/a11y-tests/dist/reports'
      artifactName: 'CodeAnalysisLogs'
    displayName: publish sarif a11y reports

  - script: |
      git config --global user.email "fabrictactical@microsoft.com"
      git config --global user.name "Fabric Tactical"
      npm run vrtest
    displayName: run VR Test
    env:
      SCREENER_API_KEY: $(screener.key)

  - script: |
      npm run check-for-changed-files
    displayName: check for change file
